### ISSUE TITLE
[Feat] Single-Window GUI: Integrate new map display wx.Panels into a AuiNotebook center pane

### ISSUE THREAD

**Issue by lindakladivova** [OSGeo/grass#1735]
**Is your feature request related to a problem? Please describe.**
This PR aims at the basic integration of the new Map Display into the center AuiNotebook pane.
It only fixes the existing functionality, does not add anything new.

Firstly several Issues were made addressing for this purpose. However, later we decided to make just one Issue with several tasks. The below-mentioned separate Issues are closed now and merged into this general Issue.

It involves several minor tasks:

- [ ]  Remove methods related to the depreciated Map Display wx.Frame. (https://github.com/OSGeo/grass/issues/1738)

- [ ]  Fix behavior when adding or switching to a new location (now it does not close previously opened map displays).(https://github.com/OSGeo/grass/issues/1737)

- [ ]  Make a newly added AuiNotebook tab active when adding a new Display tab. (https://github.com/OSGeo/grass/issues/1736)

- [ ]  Edit an existing closing event for the Display tab. This event should close the related AuiNotebook tab. (https://github.com/OSGeo/grass/issues/1741)

- [ ]  Edit an existing event for the switching between Display tabs. This event should make the related AuiNotebook tab active. (https://github.com/OSGeo/grass/issues/1744)

- [ ]  Fix an existing RenameDisplay event handle. (https://github.com/OSGeo/grass/issues/1745)

- [ ]  Fix adding and removing of the 3D View pane. Decide where should this tab go when launching 3D for the first time. (https://github.com/OSGeo/grass/issues/1738)

**Comment by lindakladivova** [comment]
Closed by https://github.com/OSGeo/grass/pull/1732.
